name: slide_puzzle

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ar_flutter_plugin: ^0.6.2
  flutter:
    sdk: flutter
  provider: ^6.0.2
  vector_map: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.3.4

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Plaster
      fonts:
        - asset: asset/fonts/plaster/Plaster-Regular.ttf
